# Generated by Django 4.2.11 on 2026-04-01 13:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Default discount percentage for this category', max_digits=5)),
            ],
            options={
                'verbose_name': 'Customer Category',
                'verbose_name_plural': 'Customer Categories',
                'db_table': 'customer_categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Customer name or company name', max_length=200)),
                ('email', models.EmailField(help_text='Primary email address', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(help_text='Phone number', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Invalid phone format')])),
                ('alt_phone', models.CharField(blank=True, help_text='Alternate phone number', max_length=20, null=True)),
                ('address', models.TextField(help_text='Street address')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID or GST number', max_length=50, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Maximum credit allowed for this customer', max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='customers_name_25d5e3_idx'), models.Index(fields=['email'], name='customers_email_92e882_idx'), models.Index(fields=['is_active', '-created_at'], name='customers_is_acti_6d1ca5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Contact Person',
                'verbose_name_plural': 'Contact Persons',
                'db_table': 'contact_persons',
            },
        ),
    ]
