# Generated by Django 5.2.12 on 2026-04-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_conversion_rate', models.DecimalField(decimal_places=2, default=100.0, help_text='Amount in ₹ required to earn 1 loyalty point', max_digits=8)),
            ],
            options={
                'verbose_name': 'Store Setting',
                'verbose_name_plural': 'Store Settings',
                'db_table': 'store_settings',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current outstanding balance owed by the customer', max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.IntegerField(default=0, help_text='Accumulated loyalty points'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary email address (Optional)', max_length=254, null=True),
        ),
    ]
