services:
  - type: web
    name: billing-erp
    runtime: docker
    plan: free
    preDeployCommand: "python manage.py migrate --noinput"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DB_ENGINE
        value: postgresql
      - key: DB_HOST
        fromDatabase:
          name: billing-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: billing-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: billing-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: billing-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: billing-db
          property: port
      - key: CELERY_BROKER_URL
        fromService:
          type: keyvalue
          name: billing-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: keyvalue
          name: billing-redis
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*" # You should update this later with your specific Render URL

  - type: keyvalue
    name: billing-redis
    plan: free
    ipAllowList: []

databases:
  - name: billing-db
    plan: free
