# Generated by Django 4.2.11 on 2026-04-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST/HSN Code', max_length=50, null=True),
        ),
    ]
