# Generated by Django 5.2.12 on 2026-04-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Scan barcode or enter manually', max_length=100, null=True),
        ),
    ]
